### ISSUE TITLE
Segmentation fault with cpu module

### ISSUE THREAD

**Issue by BenoitAverty** [jaagr/lemonbuddy#152]
Hello,

I have a segmentation fault that sometimes occur on by bottom bar. The error doesn't occur at the start, but after some time (sometimes almost immediately, sometimes after quite some time)

 Here is the trace from gdb:

```
$ LEMON_PRIMARY_MONITOR=VGA-1 gdb --args lemonbuddy bottom_primary -l info
GNU gdb (GDB) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from lemonbuddy...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/lemonbuddy bottom_primary -l info
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
warn: Disabling tray manager (reason: disabled in config)
* Starting application
[New Thread 0x7ffff36c8700 (LWP 26549)]
[New Thread 0x7ffff2ec7700 (LWP 26550)]
* Starting event loop
* Starting module/i3
[New Thread 0x7ffff26c6700 (LWP 26551)]
* Starting module/title
[New Thread 0x7ffff1ec5700 (LWP 26552)]
* Starting module/cpu
[New Thread 0x7ffff16c4700 (LWP 26554)]
* Starting module/memory
[New Thread 0x7ffff0ec3700 (LWP 26556)]
* Starting module/packages
[New Thread 0x7fffdbfff700 (LWP 26557)]
* Starting module/diskspace
[New Thread 0x7fffdb7fe700 (LWP 26558)]

Thread 6 "lemonbuddy" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff16c4700 (LWP 26554)]
0x00007ffff5cb5220 in __memcpy_ssse3 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff5cb5220 in __memcpy_ssse3 () from /usr/lib/libc.so.6
#1  0x00007ffff647db1b in std::char_traits<char>::copy (__n=49, __s2=<optimized out>, __s1=<optimized out>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:290
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__n=49, __s=<optimized out>, __d=<optimized out>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:300
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign (this=0x88d760, 
    __str=<error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:272
#4  0x000000000055138d in lemonbuddy::v2_0_0::drawtypes::progressbar::fill(unsigned int, unsigned int) ()
#5  0x000000000055167d in lemonbuddy::v2_0_0::drawtypes::progressbar::output[abi:cxx11](float) ()
#6  0x00000000004e7e48 in lemonbuddy::v2_0_0::modules::cpu_module::build(lemonbuddy::v2_0_0::builder*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const ()
#7  0x00000000004c5d2b in lemonbuddy::v2_0_0::modules::timer_module<lemonbuddy::v2_0_0::modules::cpu_module>::runner() ()
#8  0x00007ffff641531f in std::execute_native_thread_routine (__p=0x837dc0) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:83
#9  0x00007ffff5f2d454 in start_thread () from /usr/lib/libpthread.so.0
#10 0x00007ffff5c707df in clone () from /usr/lib/libc.so.6
(gdb)
```

Here is the conf (only the part related to the bar that contains the cpu module)

```
[bar/bottom_primary]
monitor = ${env:LEMON_PRIMARY_MONITOR}
width = 100%
height = 28
bottom = true

padding-left = 1
padding-right = 3

lineheight = 3

background = ${bar/top.background}
foreground = ${bar/top.foreground}

spacing = 4
separator = "  "

font-0 = ${bar/top.font-0}
font-1 = ${bar/top.font-1}

modules-left = i3
modules-center = title
modules-right = cpu memory packages diskspace

[module/memory]
type = internal/memory
format = <label> <bar-used>
label =  %percentage_used%

bar-used-width = 10
bar-used-foreground-0 = #c1cb7f
bar-used-foreground-1 = #d9c37f
bar-used-foreground-2 = #e4a48a
bar-used-foreground-3 = #ed9896
bar-used-indicator = ■
bar-used-indicator-font = 2
bar-used-indicator-foreground = #55fdf6e3
bar-used-fill = ■
bar-used-fill-font = 2
bar-used-empty = □
bar-used-empty-font = 2
bar-used-empty-foreground = #99586e75

[module/cpu]
type = internal/cpu
interval = 0.5
format = <label> <bar-load>
label =  %percentage%

bar-load-width = 10
bar-load-foreground-0 = #c1cb7f
bar-load-foreground-1 = #d9c37f
bar-load-foreground-2 = #e4a48a
bar-load-foreground-3 = #ed9896
bar-load-indicator = ■
bar-load-indicator-font = 0
bar-load-indicator-foreground = #55fdf6e3
bar-load-fill = ■
bar-load-fill-font = 0
bar-load-empty = □
bar-load-empty-font = 0
bar-load-empty-foreground = #99586e75

[module/i3]
type = internal/i3

pin-workspaces=true
index-sort=true

format = <label-state>

ws-icon-default=
ws-icon-0 = 1;  
ws-icon-1 = 2;  
ws-icon-2 = 3;  
ws-icon-3 = 9;  
ws-icon-4 = 10;  

label-focused = " %icon%%name% "
label-focused-foreground = #1d1f21
label-focused-background = #2d6c95
label-focused-underline = #ee4433
label-focused-padding = 2

label-unfocused = " %icon%%name% "
label-unfocused-padding = 2

label-visible = " %icon%%name% "
label-visible-padding = 2

label-urgent = " %icon%%name% "
label-urgent-foreground = #ee4433
label-urgent-padding = 2

[module/title]
type = custom/script
exec = xtitle -s
tail = true
maxlen = 120

[module/diskspace]
type = custom/script
exec = /home/benoit/.scripts/lemon_diskspace.sh
interval = 60

[module/packages]
type = custom/script
exec = /home/benoit/.scripts/lemon_packages.sh
interval = 60
```

**Comment by BenoitAverty** [comment]
If it helps, I noticed that the segfault seems to happen when I have a High CPU load. Maybe it occurs when the module tries to display 100% or something ?

**Comment by jaagr** [comment]
Yeah that might be the issue.. I will test the config
